suppress_failure_on_regression: false
global:
  reg_min: 10.9
  imp_min: -25.5
  benchmarks:
  dimensions:
     alloc/op:
       reg_min: 5
       imp_min: -2.47

     lost:
       reg_min: 16.78
       imp_min: -25.17

     foo:
       reg_min: 20
       imp_min: -12

per_dir:
  worker/dir.+:
    reg_min: 10
    imp_min: 15

  doc/tail.+:
    reg_min: 70
    imp_min: -58
    benchmarks:
      SendRecv/msgsize:
        reg_min: 55
        imp_min: -20

      GoParse3339InLocation:
        reg_min: 5
        imp_min: -4
